spring:
  application:
    name: Diddycart

  # Disable Docker Compose Support
  docker:
    compose:
      enabled: false

  # Kafka Configuration
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: diddycart-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.diddycart.modules.identity.events,com.diddycart.modules.sales.events,com.diddycart.common.events"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  # Email Configuration
  mail:
    host: sandbox.smtp.mailtrap.io # Use Mailtrap for dev testing
    port: 2525
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Redis Configuration
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  # Supabase DataSource Configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    # HikariCP Settings
    hikari:
      maximum-pool-size: 15
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000

  # JPA Settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": true

diddycart:
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 86400000

# Razorpay Configuration
razorpay:
  key:
    id: ${key_id}
    secret: ${key_secret}

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
  group-configs:
    - group: all
      display-name: All
      paths-to-match: /**
    - group: authentication
      display-name: authentication
      paths-to-match: /api/auth/**
    - group: product
      display-name: product
      paths-to-match: /api/products/**
    - group: cart
      display-name: cart
      paths-to-match: /api/cart/**
    - group: orders
      display-name: orders
      paths-to-match: /api/orders/**
    - group: payment
      display-name: payment
      paths-to-match: /api/payments/**
    - group: vendor
      display-name: vendor
      paths-to-match: /api/vendors/**
    - group: address
      display-name: address
      paths-to-match: /api/addresses/**
    - group: views
      display-name: views
      paths-to-match: /checkout, /payment-success, /payment-failure
